---
- name: Install required s/w's on devserver
  hosts: devserver
  tasks:
   - name: Install required s/w's
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
       - {a: openjdk-11-jdk,b: present,c: yes}
       - {a: maven,b: present,c: no}
       - {a: git,b: present, c: no}
- name: Install required s/w's on qaserver
  hosts: qaserver
  tasks:
   - name: Install required s/w's
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
       - {a: git,b: present, c: yes}
       - {a: openjdk-11-jdk,b: present,c: no}
       - {a: tomcat10,b: present,c: no}
       - {a: tomcat10-admin,b: present, c: no}
- name: Install required s/w's on prodserver
  hosts: prodserver
  tasks:
   - name: Install required s/w's
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
       - {a: tomcat10,b: present,c: yes}
       - {a: tomcat10-admin,b: present, c: no}
- name: Continuous Download and Build
  hosts: devserver
  tasks:
   - name: Download development code from github
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest:  dev-git
   - name: Create an artifact from the above code
     shell: cd dev-git;mvn package
   - name: Fetch the artifact from devserver to controller
     fetch: 
      src: dev-git/webapp/target/webapp.war
      dest: /tmp
- name: Continuous Deployment and Testing
  hosts: qaserver
  tasks:
   - name: Deploy artifact into tomcat 
     copy:
      src: /tmp/172.31.38.199/dev-git/webapp/target/webapp.war
      dest: /var/lib/tomcat10/webapps/testapp.war  
   - name: Download the selenium scripts
     git:
       repo: https://github.com/intelliqittrainings/FunctionalTesting.git
       dest: test-git
   - name: Run the selenium scripts
     shell: java -jar test-git/testing.jar
- name: Continuous Delivery
  hosts: prodserver
  tasks:
   - name: Deploy the artifact into prodserver tomcat
     copy:
      src: /tmp/172.31.38.199/dev-git/webapp/target/webapp.war
      dest: /var/lib/tomcat10/webapps/prodapp.war






